name: Build & Release

permissions:
  contents: write

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

on:
  workflow_call:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install SvelteKit Dependencies
        working-directory: web
        run: npm install

      - name: Build SvelteKit App
        working-directory: web
        run: npm run build

      - name: Debug Frontend Build Output
        run: ls -R web/build || echo "❌ No frontend build output found!"

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build Golang Backend
        working-directory: api
        run: touch .env && make build/api

      - name: Create Release Artifacts
        run: |
          mkdir -p release/api release/client
          if [ -d "api/bin" ]; then mv api/bin/** release/api; else echo "❌ Backend build output missing"; fi
          if [ -d "web/build" ]; then mv web/build/** release/client; else echo "❌ Frontend build output missing"; fi

      - name: Debug Release Artifacts
        run: ls -R release || echo "❌ No release artifacts found!"

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: release/client
          if-no-files-found: error

      - name: Upload backend Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: release/api
          if-no-files-found: error

      - name: Create TAR Archive
        run: |
          mkdir -p release
          tar -czvf release/hrflow-build.tar.gz -C release api client

      - name: Debug TAR Archive
        run: ls -lah release/hrflow-build.tar.gz || echo "❌ TAR file is missing!"

      - name: Upload TAR Archive
        uses: actions/upload-artifact@v4
        with:
          name: hrflow
          path: release/hrflow-build.tar.gz
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download hrflow TAR Archive
        uses: actions/download-artifact@v4
        with:
          name: hrflow
          path: release

      - name: Debug Downloaded Artifacts
        run: ls -R release || echo "❌ No release artifacts found after downloading!"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/hrflow-build.tar.gz
          tag_name: v0.0.${{ github.run_number }}
          body: "🚀 New release build for HRFlow SvelteKit & Go API"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
